/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp6.detodosa;

import javax.swing.JOptionPane;

/**
 *
 * @author Joaco
 */
public class PorPrecio extends javax.swing.JInternalFrame {

  

  
    

    /**
     * Creates new form PorPrecio
     */
    public PorPrecio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTPrecio1 = new javax.swing.JTextField();
        jTPrecio2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();

        setClosable(true);

        jTPrecio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTPrecio1ActionPerformed(evt);
            }
        });
        jTPrecio1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTPrecio1KeyReleased(evt);
            }
        });

        jTPrecio2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTPrecio1KeyReleased(evt);
            }
        });

        jLabel1.setText("Entre $:");

        jLabel2.setText("Listado Por Precio");

        jLabel3.setText("y");

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Descripción", "Precio", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(30, 30, 30)
                        .addComponent(jTPrecio1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addComponent(jTPrecio2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTPrecio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTPrecio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTPrecio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTPrecio1ActionPerformed
         //TODO add your handling code here:
//            private void jTPrecio1KeyReleased(java.awt.event.KeyEvent evt) {                                     
//    borrarFilas();
//        for(Producto prod:MenuGeneral.productos){
//    
//            if(prod.getDescripcion().toLowerCase().startsWith(jTprecio1.getText().toLowerCase())){
//                    modelo.addRow(new Object[]{
//                            prod.getCodigo(),
//          });
//    }                     prod.getDescripcion(),
//                            prod.getPrecio(),
//                            prod.getStock(),
//           });
//   }
//} 
    
    }//GEN-LAST:event_jTPrecio1ActionPerformed
// TODO add your handling code here:
       // private void jTprecio1KeyReleased(java.awt.event.KeyEvent evt)
    private void jTPrecio1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTPrecio1KeyReleased
//        {
//            String p1S = jTPrecio1.getText();
//             int p1=Integer.parseInt(p1S);
//            // JOptionPane.showMessageDialog(this, p1);
//            
//            String p2S = jTPrecio2.getText();
//             int p2=Integer.parseInt(p2S);
//             
//             JOptionPane.showMessageDialog(this, p2);
//            
//             for(Producto prod:MenuGeneral.productos){ 
//            if(prod.getPrecio()<p1){
//                JOptionPane.showMessageDialog(this,"adentro");
//            }
//                    modelo.addRow(new Object[]{
//                            prod.getCodigo(),
//                            prod.getDescripcion(),
//                            prod.getPrecio(),
//                            prod.getStock(),
//           });
//           
//        }
       
       

        
    }//GEN-LAST:event_jTPrecio1KeyReleased

   private void actualizarTabla() {
    tableModel.setRowCount(0); // Limpiar la tabla

    try {
        double precio1 = Double.parseDouble(jTPrecio1.getText());
        double precio2 = Double.parseDouble(jTPrecio2.getText());
        Iterable<Double> precios = null;

        for (Double precio : precios) {
            if (precio >= precio1 && precio <= precio2) {
                tableModel.addRow(new Object[]{precio});
            }
        }
    } catch (NumberFormatException e) {
        // Manejo de error si los campos no contienen números válidos
        JOptionPane.showMessageDialog(this, "Ingrese valores numéricos válidos en los campos de precio.");
    }
}


        
    
        
    

    
    
    
    
          
    

        
    

    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTPrecio1;
    private javax.swing.JTextField jTPrecio2;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables

    private static class tableModel {

        private static void setRowCount(int i) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        private static void addRow(Object[] object) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public tableModel() {
        }
    }
}
